### ISSUE TITLE
Error processing Request

### ISSUE THREAD

**Issue by On0n0k1** [fermyon/spin-url-shortener#2]
I did a simple clone of the project. Ran:

```
spin build
```

Then:

```
spin up
```

The server starts, when I connect to the ip:port, it receives the request. But has issues parsing it.

Following is the request made from the terminal:

```
$ curl -i localhost:3000/spin
HTTP/1.1 500 Internal Server Error
content-length: 0
date: Fri, 23 Sep 2022 19:42:53 GMT

```

Following is the logs from the runtime:

```
$ spin up
Serving http://127.0.0.1:3000
Available Routes:
  shortener: http://127.0.0.1:3000 (wildcard)
2022-09-23T19:42:53.174517Z ERROR spin_http_engine: Error processing request: invalid discriminant for `option`    

```

The error message is the same. Regardless of connecting to localhost:3000/spin, localhost:3000/hype, localhost:3000/abc, etc.

The crate hasn't changed in the last few months. So I think it may be some change from the latest release.

**Comment by bacongobbler** [comment]
Have you tried updating the spin SDK to a more recent version? I have a feeling the dependencies may be out of date to be used against a more recent version of Spin.

https://github.com/fermyon/spin-url-shortener/blob/e5a9f9df48dd452385681b224e7034feb026484d/Cargo.toml#L19

**Comment by bacongobbler** [comment]
You might need to update wit-bindgen-rust as well. Try taking the output from `spin new` as a reference guide.

**Comment by On0n0k1** [comment]
It worked.

I have to correct my message above. Running "spin build" results in the message "No build command found!". I have to run:

```bash
cargo build --target wasm32-wasi --release
```

And then:

```bash
spin up
```

How do we make "spin build" work?

**Comment by bacongobbler** [comment]
You will need to add a `[component.build]` section to spin.toml [as per the examples](https://github.com/fermyon/spin/blob/a4bcbd6005e955c3d22791865f4fa9972be0a3e2/examples/http-rust/spin.toml#L14-L15). It doesn't look like there's one for spin-url-shortener - likely because the project was built before `spin build` was introduced.

**Comment by On0n0k1** [comment]
It worked. Thanks a lot.

Will send a PR with the updated code later.
